### ISSUE TITLE
Is XCLogParser available as a library？

### ISSUE THREAD

**Issue by kazuhiro4949** [MobileNativeFoundation/XCLogParser#137]
I'm making a log system which stores xcode build logs.
I'd like to integrate XCLogParser into the source code with Swift Package Manager.
Does XCLogParser have an Interface to integrate other source code?

**Comment by BalestraPatrick** [comment]
For sure! You should be able to depend on it: https://github.com/MobileNativeFoundation/XCLogParser/blob/3583b8dd9f530131fc9085e4d10d76fc507732cb/Package.swift#L24-L27

If you're looking for an example, our other project `XCMetrics` depends on `XCLogParser` via SPM: https://github.com/spotify/XCMetrics/blob/8edfcfec4e8aebf374ee1d323d46b52dfa54e7ab/Package.swift#L18
