### ISSUE TITLE
Subtask.html has no data when report to html

### ISSUE THREAD

**Issue by ma125125t** [MobileNativeFoundation/XCLogParser#142]
## Command
`xclogparser parse --reporter html --file F2E3C0C0-B5A9-493D-BC52-85A59533D701.xcactivitylog `

## Reproduce:

xlogfile:[F2E3C0C0-B5A9-493D-BC52-85A59533D701.xcactivitylog.zip](https://github.com/MobileNativeFoundation/XCLogParser/files/6790435/F2E3C0C0-B5A9-493D-BC52-85A59533D701.xcactivitylog.zip)

My html result: 
[20210709143032.zip](https://github.com/MobileNativeFoundation/XCLogParser/files/6790439/20210709143032.zip)

Index.html looks well,but if we click a single task to step in.There is no data in it.

**index.html**
![image](https://user-images.githubusercontent.com/8197207/125059927-6cf09600-e0de-11eb-81ec-b9b5057ece21.png)

**subtask.html**
![image](https://user-images.githubusercontent.com/8197207/125059796-4a5e7d00-e0de-11eb-8892-2c4af444d9d2.png)

ps:If I use json reporter,it works well,there is data in subtask.

**Comment by FFFang** [comment]
find where goes wrong:
there is character "'" in my computer name, so the code execute error.
`const stepUrl = window.location.href.replace(encodeURI('fang's_MacBook_Pro_22C3BD02-CC19-4730-AE2B-0F84D9752A77_2568.html'), targetId + '.html');
`

**Comment by dhoskins** [comment]
This issue can be sidestepped by passing `--machine_name fang` as a parameter to `xclogparser`.
