### ISSUE TITLE
Could not find an SDK that supports macOS 11.4

### ISSUE THREAD

**Issue by orwater** [MobileNativeFoundation/XCLogParser#144]
I try use homebrew to install, but failed. 

 "Could not find an SDK that supports macOS 11.4.
You may have have an outdated or incompatible Xcode."

my system version is macOS 11.4,Xcode version is 12.5 

<img width="673" alt="截屏2021-07-16 下午3 11 01" src="https://user-images.githubusercontent.com/5849010/125907744-517be2ce-9cfe-4814-8fa9-ac1e5dda1787.png">

**Comment by BalestraPatrick** [comment]
Sounds like an issue with Homebrew itself or you local installation since I was able to install it correctly via Homebrew just now.
