### ISSUE TITLE
xclogparser parses the second to the latest .xcactivitylog

### ISSUE THREAD

**Issue by yongjincho92** [MobileNativeFoundation/XCLogParser#146]
As noted in the README for XCLogParser, .xcactivitylog file is generated a few seconds after the build action is completed. I added the xclogparser parse command into the build's post action and what I see is that the xclogparser parses the xcactivitylog for the second to the latest build log. 

I am using Xcode 12.5.1 and I am not sure if this is by design or a bug. Can someone also confirm that adding xclogparser as the post build action is guaranteed to wait for the latest .xcactivitylog file to be generated and then parse it?

**Comment by polac24** [comment]
Hi!
No, `XCLogParser` doesn't retry if .xcactivitylog is invalid. 

For your scenario with post build action, you can use [XCMetrics](https://github.com/spotify/XCMetrics), which actually validates .xcactivitylog and retries if is not ready yet:

https://github.com/spotify/XCMetrics/blob/0f449cc9dc328de3fcd85e08edec18f43da3a041/Sources/XCMetricsClient/Log%20Management/LogManager.swift#L128-L155

**Comment by dezinezync** [comment]
>  ...am using Xcode 12.5.1 and I am not sure if this is by design or a bug.

I can reproduce the same with Xcode Version 13.3 (13E113)

Adding something along the lines of `sleep 5;` before executing `xclogparser...` in the post-build section does not work either.

**Comment by PatrikBillgren** [comment]
Closing since the original question is answered
