### ISSUE TITLE
xcodebuild does not generate a valid xcactivitylog

### ISSUE THREAD

**Issue by BBC6BAE9** [MobileNativeFoundation/XCLogParser#156]
I use xcodebuild command to compile my project，generate new xcactivitylog, but  there is no data in it. Does anyone know how to fix it?

` xcodebuild build -project xxx.xcodeproj -scheme xxx -configuration Release -sdk iphonesimulator`

**Comment by BBC6BAE9** [comment]
Since Xcode 11, xcodebuild only generates the .xcactivitylog build logs when the option -resultBundlePath is present. If you're compiling with that command and not with Xcode, be sure to set that option to a valid path ending in .xcresult.

**Comment by CraigSiemens** [comment]
Was there anything else besides adding `-resultBundlePath` that you changed? We're running into the same issue but already have `-resultBundlePath` being passed to `xcodebuild`.
