### ISSUE TITLE
Chrome unable to load index.html with error code 5

### ISSUE THREAD

**Issue by guidedways** [MobileNativeFoundation/XCLogParser#165]
After a clean build, I'm unable to load the index.html file in Chrome. It gives me a `error code 5` - not sure if this has something to do with an internal timeout due to an "out of memory" error. When I tried compressing the generated folder, it seems to be 9GB in size (!). Is that normal? Perhaps there's far too much data generated - is there any way to trim / limit this?

**Comment by Tayphoon** [comment]
We have same issue when run xcodebuild command with flag -resultBundlePath (xcodebuild does not generate xcactivitylog without flag). Xcode log each step, create folder for example. After we call 
 ``` xclogparser parse --project <path_to_proj> --reporter html ```
xclogparser generate step html file for each of this steps. As a result xclogparser create 19741 files in directory each has 15kb size. Result report folder has 1.3Gb. If we build project usign Xcode we get small size report. 

We use Xcode 15 when building project. Could you please tell which flags we can use to reduce xcactivitylog or ignore some steps by xclogparser htm report?
