### ISSUE TITLE
Error parsing Xcode 14 log

### ISSUE THREAD

**Issue by fzwo** [MobileNativeFoundation/XCLogParser#169]
When trying to dump or parse an xcactivitylog file generated by Xcode 14, I get the following error:

> Error: Error parsing the log: Unexpected className found parsing DocumentLocation DVTMemberDocumentLocation

**Comment by akaDuality** [comment]
Example of tokens for `DVTMemberDocumentLocation`

```
  ▿ 11 : [type: className, name: "DVTMemberDocumentLocation"]
    - className : "DVTMemberDocumentLocation"
  ▿ 12 : [type: classNameRef, className: "DVTMemberDocumentLocation"]
    - classNameRef : "DVTMemberDocumentLocation"
  ▿ 13 : [type: string, value: "file:///Users/rubanov/Documents/Projects/CodeMetrics/UI/Details/Details/Details.storyboard"]
    - string : "file:///Users/rubanov/Documents/Projects/CodeMetrics/UI/Details/Details/Details.storyboard"
  ▿ 14 : [type: double, value: 0.0]
    - double : 0.0
  ▿ 15 : [type: string, value: "irs-zY-n9e"]
    - string : "irs-zY-n9e"
  ▿ 16 : [type: string, value: "Notice"]
    - string : "Notice"
  ▿ 17 : [type: list, count: 0]
    - list : 0
  - 18 : [type: nil]
```

**Comment by akaDuality** [comment]
[Sample file](https://github.com/MobileNativeFoundation/XCLogParser/files/8864396/006A79B4-1766-4613-87A0-CAB5A591805F.xcactivitylog.zip)

**Comment by akaDuality** [comment]
`DVTMemberDocumentLocation` looks simple, it's just another name for `DVTDocumentLocation`. But what is strange that some of `IDEDiagnosticActivityLogMessage` contains `Notice`, and some of them misses it.

**Comment by akaDuality** [comment]
[Draft pull request](https://github.com/MobileNativeFoundation/XCLogParser/pull/170)

**Comment by ecamacho** [comment]
Thanks @akaDuality for the PR. Can you upload again the Sample file? It is damaged and I have not been able to create a log that reproduces the issue
