### ISSUE TITLE
Error while adding XCLogParser as Swift Package

### ISSUE THREAD

**Issue by vladislovshilov** [MobileNativeFoundation/XCLogParser#173]
Hello there, first of all thank you guys so much for that tool 🙏 You did a really good research!

**The problem:**
I can't integrate it into the project. Looks like I missed some little detail.

**What I did?**
I added XCLogParser as a SwiftPackage dependency and got a couple of errors.

- In case when I add only executable file
![Executable](https://user-images.githubusercontent.com/38430226/176407422-b25e1b79-dbd7-40ea-b93a-6a7439b06920.png)
![Executable error](https://user-images.githubusercontent.com/38430226/176407123-d4253a26-ef1f-4c53-8396-59018a6f228f.png)

This is iOS project with several build targets (i.e Dev, Staging, Prod). Could it be the problem?

- In case when I add both library and executable files
![Executable/Library](https://user-images.githubusercontent.com/38430226/176407548-8857d28f-6e97-417b-9e88-6740b1ac557b.png)
![Executable/Library error](https://user-images.githubusercontent.com/38430226/176406023-02e6c2d1-03ec-41a1-85ad-2fe9132ee629.png)

**Comment by polac24** [comment]
To be clear - if want to integrate XCLogParser into your own tool, you should only set a dependency on `XCLogParser` library, not `xclogparser` executable.

**Comment by vladislovshilov** [comment]
Thanks for the response @polac24. No, I just wanted to test it in my project..
I added executable directly and ran a post-script with that. It works fine!
