### ISSUE TITLE
XCLogParser does not pick up all deprecation warnings

### ISSUE THREAD

**Issue by lgilyazov** [MobileNativeFoundation/XCLogParser#183]
I noticed that not all deprecation messages make it to the final report. I found the problem and prepared a fix. Can I create a Pull Request?

XCLogParser version: 0.2.36

<img width="1255" alt="Снимок экрана 2023-02-21 в 18 11 15" src="https://user-images.githubusercontent.com/17198014/220383219-2e873487-fd1a-4446-ae62-7d9fab8c655f.png">
<img width="1479" alt="Снимок экрана 2023-02-21 в 18 07 23" src="https://user-images.githubusercontent.com/17198014/220383301-4c725088-e6d3-4130-b753-674ecb8ca6ac.png">

**Comment by lgilyazov** [comment]
It is a fix: https://github.com/lgilyazov/XCLogParser/commit/63e320886a1ff2b7c757e55b075a47662a4be01d

**Comment by BalestraPatrick** [comment]
@lgilyazov For sure! Go ahead and create a PR and I'll review it.
