### ISSUE TITLE
Release the latest changes?

### ISSUE THREAD

**Issue by Bobbyphtr** [MobileNativeFoundation/XCLogParser#194]
There are 14 commits ahead prior to the latest release. It looks like there are some improvement for Xcode 14. 
Today is 2023, kinda surprise there are no other release to be made.

notable:
- https://github.com/MobileNativeFoundation/XCLogParser/pull/182
- https://github.com/MobileNativeFoundation/XCLogParser/pull/184
- https://github.com/MobileNativeFoundation/XCLogParser/pull/189 -> Xcode 15 related

I would like to do the version bump if you will.

**Comment by BalestraPatrick** [comment]
Thanks for the PR! New release is live: https://github.com/MobileNativeFoundation/XCLogParser/releases/tag/v0.2.37

**Comment by Bobbyphtr** [comment]
@BalestraPatrick Happy to help!
