### ISSUE TITLE
parse xcode14.3 xcactivitylog error 

### ISSUE THREAD

**Issue by yohunl** [MobileNativeFoundation/XCLogParser#209]
The latest version can parse the logs of Xcode 15.3 without any issues, but fails to parse the logs from the older Xcode 14.3. The error message is: "Error: Error parsing the log: Unexpected token parsing array of IDEActivityLogSectionAttachment: [type: classNameRef, className: 'IDEActivityLogSection']."

**Comment by rabc** [comment]
There is nothing fancy in 0.2.39 apart the fix of Xcode 15.3 new token. I guess that you can keep using the previous version until you can migrate to new Xcode.

**Comment by yohunl** [comment]
> There is nothing fancy in 0.2.39 apart the fix of Xcode 15.3 new token. I guess that you can keep using the previous version until you can migrate to new Xcode.

The issue was caused by the newly added method parseIDEActivityLogSectionAttachments. Although the older versions do not have this method, they somehow end up invoking it, which leads to confusion in the enumerator. I've attempted a fix as follows,

![image](https://github.com/MobileNativeFoundation/XCLogParser/assets/520870/418e07fd-b800-4f03-a3c3-b670fa08f7eb)


 and after verification, it works now.

**Comment by ChengJingH** [comment]
I also encountered this problem using XCLogParse v 2.0.39, in Xcode 15
。The error message is: "Error: Error parsing the log: Unexpected token parsing array of IDEActivityLogSectionAttachment: [type: classNameRef, className: 'IDEActivityLogSection']."
