### ISSUE TITLE
 Unexpected token parsing array of IDEActivityLogSectionAttachment

### ISSUE THREAD

**Issue by Gagan5278** [MobileNativeFoundation/XCLogParser#211]
Found error with xcode 15.1 

 _Unexpected token parsing array of IDEActivityLogSectionAttachment_

how to fix this issue please.

**Comment by yohunl** [comment]
https://github.com/MobileNativeFoundation/XCLogParser/issues/209     I've made a fix for this issue, which you can refer to for your modifications.

**Comment by kalebhermes** [comment]
@aleksandergrzyb now that this has been fixed, what does it look like to get a new release cut and pushed up to brew? 

Hoping to use this tool at work, and installing via brew from a script beats cloning and building 🙏

**Comment by aleksandergrzyb** [comment]
Pushed new one!

**Comment by kalebhermes** [comment]
@aleksandergrzyb thank you! I see the release listed in Github, but brew is still installing `0.2.39`.
